[build]
  command = "bundle exec jekyll build"
  publish = "_site"
  environment = { JEKYLL_ENV = "production" }

[[redirects]]
  from = "/insights"
  to = "/insight.html"
  status = 301
  force = false

[[redirects]]
  from = "/insights/"
  to = "/insight.html"
  status = 301
  force = false

